/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miumg.edu.gt.proyectotiendalafelicidad.igu;

import miumg.edu.gt.proyectotiendalafelicidad.igu.Formulario.FormClientes;
import miumg.edu.gt.proyectotiendalafelicidad.igu.Formulario.FormCompraAgregar;
import miumg.edu.gt.proyectotiendalafelicidad.igu.Formulario.FormEliminarModificarCompra;
import miumg.edu.gt.proyectotiendalafelicidad.igu.Formulario.FormEliminarModificarProducto;
import miumg.edu.gt.proyectotiendalafelicidad.igu.Formulario.FormProductoAgregar;
import miumg.edu.gt.proyectotiendalafelicidad.igu.Formulario.FormReportes;
import miumg.edu.gt.proyectotiendalafelicidad.igu.Formulario.FormUsuario;

/**
 *
 * @author Jose
 */
public class MenuAdministrador extends javax.swing.JFrame {

    private javax.swing.JDesktopPane jDesktopPrincipal;

    /**
     * Creates new form Administrador
     */
    public MenuAdministrador() {

        initComponents();

        jDesktopPrincipal = new javax.swing.JDesktopPane();
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jDesktopPrincipal, java.awt.BorderLayout.CENTER);
        //boton para salir xd ----------------------------------------------------
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu10 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnUsuarios = new javax.swing.JMenu();
        btnClientes = new javax.swing.JMenu();
        btnReportes = new javax.swing.JMenu();
        btnProductos = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        btnProductoCompra = new javax.swing.JMenu();
        btnAgregarProducto = new javax.swing.JMenu();
        MenuEliminarModificarCompra = new javax.swing.JMenu();
        btnProductoStock = new javax.swing.JMenu();
        btnAgregarPrecio = new javax.swing.JMenu();
        btnEliminarModificarProducto = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenu();
        btnSalir2 = new javax.swing.JMenuItem();

        jMenu10.setText("jMenu10");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jMenu1.setText("Administracion");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        btnUsuarios.setText("Usuarios");
        btnUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosMouseClicked(evt);
            }
        });
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(btnUsuarios);

        btnClientes.setText("Clientes");
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
        });
        jMenu1.add(btnClientes);

        jMenuBar1.add(jMenu1);

        btnReportes.setText("Reportes");
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportesMouseClicked(evt);
            }
        });
        jMenuBar1.add(btnReportes);

        btnProductos.setText("Productos");

        jMenu7.setText("ver");

        btnProductoCompra.setText("Compra");
        btnProductoCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductoCompraMouseClicked(evt);
            }
        });

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarProductoMouseClicked(evt);
            }
        });
        btnProductoCompra.add(btnAgregarProducto);

        MenuEliminarModificarCompra.setText("Modificar/Eliminar Compra");
        MenuEliminarModificarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuEliminarModificarCompraMouseClicked(evt);
            }
        });
        btnProductoCompra.add(MenuEliminarModificarCompra);

        jMenu7.add(btnProductoCompra);

        btnProductoStock.setText("stock");

        btnAgregarPrecio.setText("Producto Venta");
        btnAgregarPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarPrecioMouseClicked(evt);
            }
        });
        btnProductoStock.add(btnAgregarPrecio);

        btnEliminarModificarProducto.setText("Eliminar/Modificar Producto");
        btnEliminarModificarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarModificarProductoMouseClicked(evt);
            }
        });
        btnProductoStock.add(btnEliminarModificarProducto);

        jMenu7.add(btnProductoStock);

        btnProductos.add(jMenu7);

        jMenuBar1.add(btnProductos);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnSalir2.setText("salir");
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });
        btnSalir.add(btnSalir2);

        jMenuBar1.add(btnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosMouseClicked
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormUsuario formUsuario = new FormUsuario();
        jDesktopPrincipal.add(formUsuario);
        formUsuario.setVisible(true);
    }//GEN-LAST:event_btnUsuariosMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

    }//GEN-LAST:event_jMenu1MouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormClientes formClientes = new FormClientes();
        jDesktopPrincipal.add(formClientes);
        formClientes.setVisible(true);
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseClicked
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormReportes formReportes = new FormReportes();
        jDesktopPrincipal.add(formReportes);
        formReportes.setVisible(true);
    }//GEN-LAST:event_btnReportesMouseClicked

    private void btnProductoCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductoCompraMouseClicked

    }//GEN-LAST:event_btnProductoCompraMouseClicked

    private void btnAgregarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarProductoMouseClicked
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormCompraAgregar formCompraAgregar = new FormCompraAgregar();
        jDesktopPrincipal.add(formCompraAgregar);
        formCompraAgregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarProductoMouseClicked

    private void MenuEliminarModificarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuEliminarModificarCompraMouseClicked
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormEliminarModificarCompra formEliminarModificarCompra = new FormEliminarModificarCompra();
        jDesktopPrincipal.add(formEliminarModificarCompra);
        formEliminarModificarCompra.setVisible(true);
    }//GEN-LAST:event_MenuEliminarModificarCompraMouseClicked

    private void btnEliminarModificarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarModificarProductoMouseClicked
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormEliminarModificarProducto formEliminarModificarProducto = new FormEliminarModificarProducto();
        jDesktopPrincipal.add(formEliminarModificarProducto);
        formEliminarModificarProducto.setVisible(true);
    }//GEN-LAST:event_btnEliminarModificarProductoMouseClicked

    private void btnAgregarPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarPrecioMouseClicked
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormProductoAgregar formProductoAgregar = new FormProductoAgregar();
        jDesktopPrincipal.add(formProductoAgregar);
        formProductoAgregar.setVisible(true);
    }//GEN-LAST:event_btnAgregarPrecioMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        new Login().setVisible(true); 
        this.dispose();

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
       new Login().setVisible(true);
        MenuAdministrador.this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuEliminarModificarCompra;
    private javax.swing.JMenu btnAgregarPrecio;
    private javax.swing.JMenu btnAgregarProducto;
    private javax.swing.JMenu btnClientes;
    private javax.swing.JMenu btnEliminarModificarProducto;
    private javax.swing.JMenu btnProductoCompra;
    private javax.swing.JMenu btnProductoStock;
    private javax.swing.JMenu btnProductos;
    private javax.swing.JMenu btnReportes;
    private javax.swing.JMenu btnSalir;
    private javax.swing.JMenuItem btnSalir2;
    public javax.swing.JMenu btnUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
